[package]
name = "ctx-pick"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.5.0"
clap = { version = "4.5.39", features = ["derive"] }
console = "0.15.11"
pathdiff = "0.2.3"
thiserror = "2.0.12"
walkdir = "2.5.0"
